# Generated by Django 5.0.6 on 2024-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingstatus',
            name='status',
            field=models.TextField(default=False, verbose_name='Статус попытки'),
        ),
    ]
