# Generated by Django 5.0.6 on 2024-06-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец рассылки'),
        ),
    ]
