# Generated by Django 5.0.6 on 2024-06-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsettings_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingstatus',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('fail', 'неуспешно')], verbose_name='Статус попытки'),
        ),
    ]
