# Generated by Django 5.0.6 on 2024-06-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='setting_status',
            field=models.CharField(choices=[('Create', 'Создана'), ('Started', 'Отправлена'), ('Completed', 'Завершена')], default='Create', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
