# Generated by Django 5.0.6 on 2024-07-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_mailingmessage_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('change_mailingsettings_setting_status', 'Can change mailingsettings setting_status')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылок'},
        ),
    ]
