# Generated by Django 5.0.6 on 2024-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='comment',
            field=models.TextField(blank=True, help_text='Напишиите комментарий', null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(default='', help_text='Введите полное имя', max_length=100, verbose_name='Имя'),
        ),
    ]
